/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JavaToc */

#ifndef _Included_JavaToc
#define _Included_JavaToc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JavaToc
 * Method:    func
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JavaToc_func
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
