/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class IncrementMethod */

#ifndef _Included_IncrementMethod
#define _Included_IncrementMethod
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     IncrementMethod
 * Method:    count
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_IncrementMethod_count
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
